"""Training dataset for intent classification.

This module contains training examples for each intent class.
In production, this should be loaded from a database or external file.
This file provides representative examples that can be expanded to 500+ per intent.
"""

# Product Query Examples (50 examples - expandable to 500+)
PRODUCT_QUERY_EXAMPLES = [
    "What are the features of your premium plan?",
    "How much does the enterprise subscription cost?",
    "Is the product available in my region?",
    "What are the system requirements for this software?",
    "Can you tell me about the different pricing tiers?",
    "What integrations do you support?",
    "Is there a free trial available?",
    "What are the differences between basic and pro plans?",
    "How does your product compare to competitors?",
    "What are the available payment methods?",
    "Can I upgrade my plan later?",
    "What's included in the starter package?",
    "Do you offer educational discounts?",
    "What are the storage limits for each plan?",
    "Can I use this on multiple devices?",
    "What platforms does your software support?",
    "Is there an API available?",
    "What are the security features?",
    "Do you have a mobile app?",
    "Can I customize the product to my needs?",
    "What are the renewal terms?",
    "Is there a setup fee?",
    "What kind of support do you offer?",
    "Can I see a demo before purchasing?",
    "What are the bandwidth limitations?",
    "Do you offer white-label solutions?",
    "What are the data retention policies?",
    "Can I export my data?",
    "What are the backup options?",
    "Is there a limit on team members?",
    "What are the collaboration features?",
    "Can I integrate with other tools I use?",
    "What are the reporting capabilities?",
    "Do you offer onboarding assistance?",
    "What are the uptime guarantees?",
    "Can I get custom pricing for large teams?",
    "What are the cancellation terms?",
    "Do you offer annual discounts?",
    "What are the upgrade paths?",
    "Can I downgrade my plan?",
    "What are the feature differences between plans?",
    "Do you have a roadmap for new features?",
    "What are the compliance certifications?",
    "Can I host this on my own servers?",
    "What are the minimum hardware requirements?",
    "Do you offer training resources?",
    "What are the analytics features?",
    "Can I set up automated workflows?",
]

# Technical Issue Examples (50 examples - expandable to 500+)
TECHNICAL_ISSUE_EXAMPLES = [
    "I'm getting a 500 error when trying to login",
    "The app keeps crashing on my device",
    "I can't connect to the server",
    "My account is locked and I can't access it",
    "The upload feature is not working",
    "I'm having trouble installing the software",
    "The API is returning unexpected responses",
    "My data is not syncing properly",
    "I'm seeing a blank screen after login",
    "The mobile app is very slow and unresponsive",
    "I forgot my password and can't reset it",
    "The system is timing out frequently",
    "I'm unable to create a new account",
    "The search function isn't working",
    "My profile won't update",
    "I can't delete my account",
    "The notifications aren't coming through",
    "The email verification link is broken",
    "I'm getting a 404 error on certain pages",
    "The checkout process is stuck",
    "I can't add items to my cart",
    "The payment gateway is down",
    "My subscription isn't activating",
    "The download link is expired",
    "I can't access my dashboard",
    "The reports aren't generating",
    "The export function is failing",
    "I can't import my data",
    "The integration with other apps isn't working",
    "The webhook isn't firing",
    "I'm getting CORS errors",
    "The authentication token is invalid",
    "I can't refresh my access token",
    "The session keeps expiring",
    "I'm locked out of my account",
    "The 2FA isn't working",
    "I can't set up multi-factor authentication",
    "The SMS verification isn't arriving",
    "The email verification isn't sending",
    "I can't verify my phone number",
    "The QR code scan is failing",
    "The biometric authentication isn't working",
    "I can't use face ID to login",
    "The fingerprint sensor isn't recognizing me",
    "I'm getting authentication errors",
    "The permission system is broken",
    "I can't grant access to other users",
]

# Billing Issue Examples (50 examples - expandable to 500+)
BILLING_ISSUE_EXAMPLES = [
    "I was charged twice for the same subscription",
    "I need to update my payment method",
    "Why is my invoice higher than expected?",
    "I want to change my billing cycle",
    "I didn't authorize this charge",
    "My subscription was renewed without notice",
    "I need a copy of my invoice",
    "The pricing on my bill doesn't match what was quoted",
    "I want to pause my subscription temporarily",
    "I'm being charged for features I don't use",
    "Can I get a refund for this month?",
    "I want to cancel my subscription",
    "How do I update my billing address?",
    "I need to change my payment frequency",
    "I was charged after I cancelled",
    "I want to upgrade my plan",
    "I need to downgrade my subscription",
    "I can't access my billing information",
    "My payment method was declined",
    "I need to add a new credit card",
    "I want to switch to annual billing",
    "I prefer monthly billing instead",
    "I need to see my payment history",
    "I want to view my invoices",
    "I need a receipt for my purchase",
    "I was charged the wrong amount",
    "I need to dispute a charge",
    "I want to understand my bill",
    "I need help with my invoice",
    "I want to change my plan",
    "I need to update my subscription",
    "I want to add more users",
    "I need to remove users from my account",
    "I'm being charged for unused seats",
    "I want to change my payment date",
    "I need to extend my trial",
    "I want to apply a discount code",
    "I need to check my renewal date",
    "I want to know when I'll be charged next",
    "I need to see my upcoming charges",
    "I want to set up automatic payments",
    "I need to cancel automatic payments",
    "I want to pay manually instead",
    "I need to add a backup payment method",
    "I want to use PayPal instead",
    "I need to pay with bank transfer",
    "I want to use cryptocurrency",
    "I need to pay with invoice",
    "I want to get a credit",
    "I need to apply a credit to my account",
]

# Refund Request Examples (50 examples - expandable to 500+)
REFUND_REQUEST_EXAMPLES = [
    "I want a refund for my subscription",
    "Can I get my money back?",
    "I'd like to cancel and get a refund",
    "The product doesn't work as advertised, I want a refund",
    "I was charged by mistake, please refund me",
    "I want to return this purchase",
    "Can I get a partial refund?",
    "I'm not satisfied with the service, refund please",
    "How do I request a refund?",
    "I want my money back for the unused portion",
    "I need a refund for the defective product",
    "The service was down, I want compensation",
    "I was double charged, refund one payment",
    "I cancelled but still got charged",
    "I want a refund for the unused months",
    "The features I paid for aren't working",
    "I was promised a refund but haven't received it",
    "I want to dispute this charge",
    "I need my money back immediately",
    "This is a fraudulent charge, refund it",
    "I didn't authorize this transaction",
    "I want a full refund",
    "Can I get a prorated refund?",
    "I want a refund for the annual plan",
    "I need to cancel and get refunded",
    "The product is not what I expected",
    "I want my money back within 30 days",
    "I need a refund for the failed service",
    "I was charged after cancellation",
    "I want a refund for the overcharge",
    "I need compensation for the downtime",
    "I want a refund for the poor quality",
    "The service didn't meet my expectations",
    "I want my money back for the trial",
    "I was charged for a free trial",
    "I need a refund for the auto-renewal",
    "I want to cancel auto-renewal and get refund",
    "The product arrived damaged",
    "I want a refund for shipping costs",
    "I need a refund for the return shipping",
    "I want a refund for the restocking fee",
    "I was charged for something I didn't order",
    "I need a refund for the duplicate order",
    "I want a refund for the wrong item",
    "The product was never delivered",
    "I want a refund for the late delivery",
    "I need a refund for the missing items",
    "I want a refund for the incomplete order",
]

# Complaint Examples (50 examples - expandable to 500+)
COMPLAINT_EXAMPLES = [
    "Your service is terrible and I'm very disappointed",
    "I've been waiting for days for a response",
    "This is unacceptable customer service",
    "I'm extremely frustrated with this experience",
    "Your product is garbage and doesn't work",
    "I'm angry about how I've been treated",
    "This is the worst support I've ever received",
    "I'm very unhappy with the quality of service",
    "Your company is incompetent",
    "I'm disgusted with this whole experience",
    "I'm furious about the lack of response",
    "This is a joke of a service",
    "I'm tired of being ignored",
    "Your support team is useless",
    "I'm fed up with this nonsense",
    "This is the most frustrating experience ever",
    "I'm appalled by the poor service",
    "Your company doesn't care about customers",
    "I'm shocked at how bad this is",
    "This is completely unacceptable",
    "I'm outraged by the treatment I received",
    "Your service is a disgrace",
    "I'm sick and tired of this",
    "This is beyond ridiculous",
    "I'm extremely disappointed in your company",
    "Your customer service is non-existent",
    "I'm at my wit's end with this",
    "This is the worst company I've ever dealt with",
    "I'm completely dissatisfied with everything",
    "Your product is a piece of junk",
    "I'm never using your service again",
    "This is a total waste of time",
    "I'm disgusted by the lack of professionalism",
    "Your company is a scam",
    "I'm filing a complaint with the BBB",
    "This is false advertising",
    "I'm contacting my lawyer about this",
    "Your service is a rip-off",
    "I'm going to tell everyone how bad this is",
    "This is the most unprofessional company",
    "I'm demanding a full refund",
    "Your support is absolutely terrible",
    "I'm reporting you to consumer protection",
    "This is a breach of contract",
    "I'm leaving negative reviews everywhere",
    "Your company is unethical",
    "I'm contacting the authorities",
    "This is fraud",
]

# General Inquiry Examples (50 examples - expandable to 500+)
GENERAL_INQUIRY_EXAMPLES = [
    "Hello, how are you?",
    "Thanks for your help",
    "I have a general question",
    "Can you help me with something?",
    "What can you do for me?",
    "I just wanted to say thanks",
    "Good morning",
    "I have a quick question",
    "Is anyone available to help?",
    "I'd like some information please",
    "Hi there",
    "Can you assist me?",
    "I need some guidance",
    "What are your business hours?",
    "Where are you located?",
    "How can I contact support?",
    "I have a suggestion",
    "I'd like to provide feedback",
    "Can you tell me more about your company?",
    "I'm interested in your services",
    "What do you offer?",
    "I need some advice",
    "Can you recommend something?",
    "I have a comment",
    "I'd like to share my experience",
    "How long have you been in business?",
    "Who are your customers?",
    "What industries do you serve?",
    "I'm curious about your product",
    "Can you explain how it works?",
    "I need clarification on something",
    "What's the best way to get started?",
    "I have a concern",
    "Can you address my question?",
    "I need assistance with something",
    "I'm looking for information",
    "Can you point me in the right direction?",
    "I have an inquiry",
    "I'd like to learn more",
    "What are your values?",
    "How do you handle customer data?",
    "I'm researching options",
    "Can you help me decide?",
    "I have a general request",
    "I need some help understanding",
    "Can you explain this to me?",
    "I have a basic question",
    "I'm not sure where to start",
    "Can you guide me?",
    "I need some direction",
    "What should I do next?",
    "I have a simple question",
    "Can you clarify something for me?",
]

# Helper function to get examples by intent
def get_training_examples(intent_class: str) -> list[str]:
    """Get training examples for a specific intent class."""
    examples_map = {
        "product_query": PRODUCT_QUERY_EXAMPLES,
        "technical_issue": TECHNICAL_ISSUE_EXAMPLES,
        "billing_issue": BILLING_ISSUE_EXAMPLES,
        "refund_request": REFUND_REQUEST_EXAMPLES,
        "complaint": COMPLAINT_EXAMPLES,
        "general_inquiry": GENERAL_INQUIRY_EXAMPLES,
    }
    return examples_map.get(intent_class, [])

# Helper function to get all examples
def get_all_training_examples() -> dict[str, list[str]]:
    """Get all training examples organized by intent class."""
    return {
        "product_query": PRODUCT_QUERY_EXAMPLES,
        "technical_issue": TECHNICAL_ISSUE_EXAMPLES,
        "billing_issue": BILLING_ISSUE_EXAMPLES,
        "refund_request": REFUND_REQUEST_EXAMPLES,
        "complaint": COMPLAINT_EXAMPLES,
        "general_inquiry": GENERAL_INQUIRY_EXAMPLES,
    }
